#!/usr/bin/env bash
# Auto-generated by test_startqemu for the 'qemu1' (i386) VM.
# Launches QEMU with the same parameters the test runner used, so
# you can start an equivalent instance by hand on the test machine.
set -euo pipefail

exec qemu-system-i386 \
    -m \
    4M \
    -monitor \
    tcp:127.0.0.1:55555,server,nowait \
    -qmp \
    tcp:127.0.0.1:56555,server,nowait \
    -vga \
    std \
    -fda \
    /testsrc/sourcedir/pacific_c_bat/newfloppy.img \
    -drive \
    file=/testsrc/sourcedir/pacific_c_bat/hdd.qcow2,if=ide,index=0,media=disk
