import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
TESTSRC_HELPERDIR = "/testsrc/pyhelpers"
if TESTSRC_HELPERDIR not in sys.path:
    sys.path.insert(0, TESTSRC_HELPERDIR)

from apphelpers import init_test_env


# vga-malloc-tester -- second test in this parent container (after
# vga-fractal-fb). it verifies eclipse_rt.c's bump allocator free() doesn't
# reclaim, the arena has a fixed capacity, calloc's nmemb*size overflows
# silently, and the allocator's own bounds check overflows the same way,
# letting an allocation alias an earlier one. 
#
# Unlike fractal.c, this program halts on its own and prints a final
# "MALLOCTEST: PASS"/"FAIL" verdict. The card shows a live status display
# while it runs (title, heap byte-layout grid, rotating log);
# verify_malloctest.py OCR-decodes the final frame and diffs it against a
# byte-for-byte replay of main()'s calls.

CONFIG = {
    "parent": "xp5_nova_fpgademo",
    "projdir": "xp5_nova_fpgademo",
    "instance_name": "nova1",
    "function": "vga_malloc_tester",
    "live_sink": "/dev/shm/novafb-xp5malloctest",
    "projbasedir": "/testsrc/sourcedir/",
    "structure": {
        "project": {
            "_rel": "{projdir}",
            "out_dir": {
                "_rel": "output"
            }
        }
    },
    "steps": [
        {
            "action": "test_start_novafb_monitor",
            "param": {
                "name": "novafb_monitor",
                "live_path": "{live_sink}",
                "scale": 0,
                "require_success": False,
                "keep_open": False
            },
            "subaction": ""
        },
        # Compile+assemble src/malloctest.c through the nova-llvm-backend
        # toolchain live, in-run -- see
        # pyhelpers/simhhelpers.compile_via_nova_llvm. Unlike fractal/
        # cuberotate, footer has both "go 100" and "quit": main() actually
        # returns here, so "quit" is reached.
        {
            "action": "test_cully_llvm_compile",
            "description": "src/malloctest.c -> gen/malloctest.ini via nova-cc -t nova3",
            "param": {
                "src_path": "{projbasedir}{projdir}/src/malloctest.c",
                "out_path": "{projbasedir}{projdir}/gen/malloctest.ini",
                "cpu": "nova3",
                "header_lines": [
                    "; malloc/free/calloc tester for this platform's runtime",
                    "; allocator -- see src/malloctest.c for what each phase",
                    "; checks and why.",
                    "; GENERATED by the test_cully_llvm_compile step from",
                    "; src/malloctest.c via nova-llvm-backend -- do not edit by hand.",
                    "set fb width=640",
                    "set fb height=480",
                    "set fb prefix=output/malloctest"
                ],
                "footer_lines": ["go 100", "quit"]
            },
            "subaction": ""
        },
        {
            "action": "test_startnovasimh",
            "description": "src/malloctest.c, compiled via nova-llvm-backend "
                           "(nova-cc -t nova3) and run against "
                           "../nova_fb/bin/dgnova-fb for the FB device",
            "param": {
                "name": "nova1",
                "binary": "{projbasedir}nova_fb/bin/dgnova-fb",
                "script_path": "{projbasedir}{projdir}/gen/malloctest.ini",
                "cwd": "{projbasedir}{projdir}",
                "boot_rdos": False,
                "live_path": "{live_sink}"
            },
            "subaction": ""
        },
        {
            "action": "test_novascreensearch",
            "description": "Check malloctest printed a final PASS/FAIL "
                           "verdict to its console",
            "param": {
                "name": "nova1",
                "successphrase": "MALLOCTEST: PASS",
                "failphrase": "MALLOCTEST: FAIL",
                "timeout": 15,
                "require_success": True
            },
            "subaction": ""
        },
        {
            "action": "test_attach_screenshot",
            "param": {
                "image_path": "{projbasedir}{projdir}/output/malloctest0008.png",
                "name": "fb",
                "scale": 2
            },
            "subaction": ""
        },
        # --- assert on the pixels, not just the console ---------------------
        {
            "action": "test_hostbuild",
            "param": {
                "command": "python3 verify_malloctest.py",
                "cwd": "{projbasedir}{projdir}",
                "timeout": 120
            },
            "subaction": ""
        },
        {
            "action": "test_terminate_all",
            "param": {},
            "subaction": ""
        },
    ],
}

PATHS = init_test_env(CONFIG, __name__)
