import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
TESTSRC_HELPERDIR = "/testsrc/pyhelpers"
if TESTSRC_HELPERDIR not in sys.path:
    sys.path.insert(0, TESTSRC_HELPERDIR)

from apphelpers import init_test_env


# vga-cuberotate -- third test in this parent container. Same toolchain
# and card as the other two tests.
#
# A rotating wireframe cube -- see src/cuberotate.c's header comment for
# the derivation: rotate around X then Y, perspective-project, draw 12
# edges, all in 16-bit fixed-point (no math.h, no float).
#
# THE TIMER: the Nova's interval clock (device 014, "RTC") ticks at 60Hz.
# The program waits one tick per frame as a vsync-style limiter, and
# every 300 ticks (5s) recomputes the average ms/frame shown in the
# corner, hand-blitted with a tiny 3x5 font.
#
# Like fractal.c this never halts, so there's no fixed frame count, and
# the corner text is non-deterministic (real wall-clock time between RTC
# ticks). verify_cuberotate.py recomputes the wireframe exactly using the
# same fixed-point arithmetic, and only OCRs the corner for plausibility.
# See ../nova_fb/__testlist__nova_fb_fractal.py for why pause_on is used
# instead of keep_open, and why the assertions run before the final
# pause_on teardown.

CONFIG = {
    "parent": "xp5_nova_fpgademo",
    "projdir": "xp5_nova_fpgademo",
    "instance_name": "nova1",
    "function": "vga_cuberotate",
    "live_sink": "/dev/shm/novafb-xp5cuberotate",
    "projbasedir": "/testsrc/sourcedir/",
    "structure": {
        "project": {
            "_rel": "{projdir}",
            "out_dir": {
                "_rel": "output"
            }
        }
    },
    "steps": [
        {
            "action": "test_start_novafb_monitor",
            "param": {
                "name": "novafb_monitor",
                "live_path": "{live_sink}",
                "scale": 0,
                "require_success": False,
                "keep_open": False
            },
            "subaction": ""
        },
        # Compile+assemble src/cuberotate.c through the nova-llvm-backend
        # toolchain live, in-run -- see
        # pyhelpers/simhhelpers.compile_via_nova_llvm. main() never
        # returns, so no "quit" is reached after "go 100".
        {
            "action": "test_cully_llvm_compile",
            "description": "src/cuberotate.c -> gen/cuberotate.ini via nova-cc -t nova3",
            "param": {
                "src_path": "{projbasedir}{projdir}/src/cuberotate.c",
                "out_path": "{projbasedir}{projdir}/gen/cuberotate.ini",
                "cpu": "nova3",
                "header_lines": [
                    "; Rotating wireframe cube (fixed-point, no libm/no FPU)",
                    "; RTC-paced (device 014), frametime corner every 5s --",
                    "; see src/cuberotate.c. NEVER HALTS.",
                    "; GENERATED by the test_cully_llvm_compile step from",
                    "; src/cuberotate.c via nova-llvm-backend -- do not edit by hand.",
                    "set fb width=640",
                    "set fb height=480",
                    "set fb prefix=output/cuberotate"
                ],
                "footer_lines": ["go 100"]
            },
            "subaction": ""
        },
        {
            "action": "test_startnovasimh",
            "description": "src/cuberotate.c, compiled via nova-llvm-backend "
                           "(nova-cc -t nova3) and run against "
                           "../nova_fb/bin/dgnova-fb for the FB device",
            "param": {
                "name": "nova1",
                "binary": "{projbasedir}nova_fb/bin/dgnova-fb",
                "script_path": "{projbasedir}{projdir}/gen/cuberotate.ini",
                "cwd": "{projbasedir}{projdir}",
                "boot_rdos": False,
                "live_path": "{live_sink}"
            },
            "subaction": ""
        },
        # No successphrase to wait for -- the program never prints to the
        # console. This only catches a script that failed to load.
        {
            "action": "test_novascreensearch",
            "param": {
                "name": "nova1",
                "failphrase": "Invalid argument",
                "timeout": 5,
                "require_success": False
            },
            "subaction": ""
        },
        # Long enough to see real rotation AND at least one 5-second
        # frametime report (300 ticks at the RTC's default 60Hz).
        {
            "action": "test_wait_for_seconds",
            "param": {
                "seconds": 8,
                "reason": "let the cube rotate through several frames and "
                          "past the first frametime report before checking"
            },
            "subaction": ""
        },
        {
            "action": "test_attach_screenshot",
            "param": {
                "image_path": "{projbasedir}{projdir}/output/cuberotate000[1-4].png",
                "name": "fb",
                "scale": 1
            },
            "subaction": ""
        },
        # --- assert on the pixels, not just the console ---------------------
        {
            "action": "test_hostbuild",
            "param": {
                "command": "python3 verify_cuberotate.py",
                "cwd": "{projbasedir}{projdir}",
                "timeout": 120
            },
            "subaction": ""
        },
        # --- handover ---------------------------------------------------
        # Every automated check above already passed. pause_on turns this
        # teardown into a breakpoint so someone reviewing interactively
        # can keep watching it rotate.
        {
            "action": "test_terminate_all",
            "param": {},
            "subaction": "",
            "pause_on": True
        },
    ],
}

PATHS = init_test_env(CONFIG, __name__)
