import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
TESTSRC_HELPERDIR = "/testsrc/pyhelpers"
if TESTSRC_HELPERDIR not in sys.path:
    sys.path.insert(0, TESTSRC_HELPERDIR)

from apphelpers import init_test_env


# vga-fractal-fb -- the first test in this parent container.
#
# Unlike sourcedir/nova_fb's own fractal demo (hand-assembled octal), this
# is real C (src/fractal.c) compiled through cullyrichard's
# nova-llvm-backend, then assembled by dgasm. gen_fractal.py does the
# build. See src/fractal.c's header comment for the algorithm and how it
# drives the card's IOT bus.
#
# It never halts . main()'s outer loop has no exit 

CONFIG = {
    "parent": "xp5_nova_fpgademo",
    "projdir": "xp5_nova_fpgademo",
    "instance_name": "nova1",
    "function": "vga_fractal_fb",
    "live_sink": "/dev/shm/novafb-xp5fractal",
    "projbasedir": "/testsrc/sourcedir/",
    "structure": {
        "project": {
            "_rel": "{projdir}",
            "out_dir": {
                "_rel": "output"
            }
        }
    },
    "steps": [
        {
            "action": "test_start_novafb_monitor",
            "param": {
                "name": "novafb_monitor",
                "live_path": "{live_sink}",
                "scale": 0,
                "require_success": False,
                "keep_open": False
            },
            "subaction": ""
        },
        # Compile+assemble src/fractal.c through the nova-llvm-backend
        # toolchain live, in-run -- see
        # pyhelpers/simhhelpers.compile_via_nova_llvm. main() never
        # returns, so there's no "quit" to reach after "go 100".
        {
            "action": "test_cully_llvm_compile",
            "description": "src/fractal.c -> gen/fractal.ini via nova-cc -t nova3",
            "param": {
                "src_path": "{projbasedir}{projdir}/src/fractal.c",
                "out_path": "{projbasedir}{projdir}/gen/fractal.ini",
                "cpu": "nova3",
                "header_lines": [
                    "; Title card (nova_fb char mode, built-in ROM) then a",
                    "; continuously scrolling AND fractal -- see src/fractal.c.",
                    "; GENERATED by the test_cully_llvm_compile step from",
                    "; src/fractal.c via nova-llvm-backend -- do not edit by hand.",
                    "set fb width=640",
                    "set fb height=480",
                    "set fb prefix=output/fractal"
                ],
                "footer_lines": ["go 100"]
            },
            "subaction": ""
        },
        {
            "action": "test_startnovasimh",
            "description": "src/fractal.c, compiled via nova-llvm-backend "
                           "(nova-cc -t nova3) and run against "
                           "../nova_fb/bin/dgnova-fb for the FB device",
            "param": {
                "name": "nova1",
                "binary": "{projbasedir}nova_fb/bin/dgnova-fb",
                "script_path": "{projbasedir}{projdir}/gen/fractal.ini",
                "cwd": "{projbasedir}{projdir}",
                "boot_rdos": False,
                "live_path": "{live_sink}"
            },
            "subaction": ""
        },
        # No successphrase to wait for -- the program never prints to the
        # console. This only catches a script that failed to load.
        {
            "action": "test_novascreensearch",
            "param": {
                "name": "nova1",
                "failphrase": "Invalid argument",
                "timeout": 5,
                "require_success": False
            },
            "subaction": ""
        },
        # Let it actually scroll for a few seconds before anything checks
        # it. nova1 stays running through every step below.
        {
            "action": "test_wait_for_seconds",
            "param": {
                "seconds": 3,
                "reason": "let the AND-scroll run so multiple frames land "
                          "in output/ and the live sink before checking them"
            },
            "subaction": ""
        },
        # --- show it in the report -------------------------------------------
        {
            "action": "test_attach_screenshot",
            "param": {
                "image_path": "{projbasedir}{projdir}/output/fractal000[1-4].png",
                "name": "fb",
                "scale": 2
            },
            "subaction": ""
        },
        # --- assert on the pixels, not just the console ---------------------
        {
            "action": "test_hostbuild",
            "param": {
                "command": "python3 verify_fractal.py",
                "cwd": "{projbasedir}{projdir}",
                "timeout": 120
            },
            "subaction": ""
        },
        # --- handover ---------------------------------------------------
        # Every automated check above already passed. pause_on turns this
        # teardown into a breakpoint so someone reviewing interactively
        # can keep watching the scroll.
        {
            "action": "test_terminate_all",
            "param": {},
            "subaction": "",
            "pause_on": True
        },
    ],
}

PATHS = init_test_env(CONFIG, __name__)
