#!/usr/bin/env python3
"""Build gen/fractal.ini from src/fractal.c through cullyrichard's
nova-llvm-backend, then add the "set fb ..." header to configure the
framebuffer card.

The actual compile lives in pyhelpers/simhhelpers.compile_via_nova_llvm,
shared with dispatch_functions' test_cully_llvm_compile step and
../cully_llvm/regen_ctestsuite.py -- this script is a thin CLI wrapper
around it, for offline regeneration outside a test run.

Requires ../cully_llvm/_toolchain/ already built -- see
../cully_llvm/NOTES.txt.

Usage: python3 gen_fractal.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TESTSRC_HELPERDIR = "/testsrc/pyhelpers"
if TESTSRC_HELPERDIR not in sys.path:
    sys.path.insert(0, TESTSRC_HELPERDIR)
from simhhelpers import compile_via_nova_llvm

SRC = os.path.join(HERE, "src", "fractal.c")
GEN_DIR = os.path.join(HERE, "gen")
OUT_INI = os.path.join(GEN_DIR, "fractal.ini")

WIDTH = 640
HEIGHT = 480
PREFIX = "output/fractal"

HEADER_LINES = [
    "; Title card (nova_fb char mode, built-in ROM) then a",
    "; continuously scrolling AND fractal -- see src/fractal.c.",
    "; GENERATED BY gen_fractal.py from src/fractal.c via",
    "; nova-llvm-backend -- do not edit by hand.",
    "set fb width=%d" % WIDTH,
    "set fb height=%d" % HEIGHT,
    "set fb prefix=%s" % PREFIX,
]

# No "quit" here: fractal.c's main() never returns, so "go 100" never
# hands control back to the SimH command processor.
FOOTER_LINES = ["go 100"]


def build():
    ok, msg = compile_via_nova_llvm(
        SRC, OUT_INI, cpu="nova3",
        header_lines=HEADER_LINES, footer_lines=FOOTER_LINES, timeout=120,
    )
    if not ok:
        sys.exit(msg)
    print(msg)


if __name__ == "__main__":
    build()
