#!/usr/bin/env python3
"""Build gen/cuberotate.ini from src/cuberotate.c -- same shape as
gen_fractal.py/gen_malloctest.py: nova-cc, then the "set fb ..." header.

The actual compile lives in pyhelpers/simhhelpers.compile_via_nova_llvm,
shared with __testlist__vga_cuberotate.py's test_cully_llvm_compile step
and ../cully_llvm/regen_ctestsuite.py -- this script is a thin CLI wrapper
around it, for offline regeneration outside a test run.

Requires ../cully_llvm/_toolchain/ already built -- see
../cully_llvm/NOTES.txt.

Usage: python3 gen_cuberotate.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TESTSRC_HELPERDIR = "/testsrc/pyhelpers"
if TESTSRC_HELPERDIR not in sys.path:
    sys.path.insert(0, TESTSRC_HELPERDIR)
from simhhelpers import compile_via_nova_llvm

SRC = os.path.join(HERE, "src", "cuberotate.c")
GEN_DIR = os.path.join(HERE, "gen")
OUT_INI = os.path.join(GEN_DIR, "cuberotate.ini")

WIDTH = 640
HEIGHT = 480
PREFIX = "output/cuberotate"

HEADER_LINES = [
    "; Rotating wireframe cube (fixed-point, no libm/no FPU)",
    "; RTC-paced (device 014), frametime corner every 5s --",
    "; see src/cuberotate.c. NEVER HALTS.",
    "; GENERATED BY gen_cuberotate.py from src/cuberotate.c via",
    "; nova-llvm-backend -- do not edit by hand.",
    "set fb width=%d" % WIDTH,
    "set fb height=%d" % HEIGHT,
    "set fb prefix=%s" % PREFIX,
]

# main()'s outer loop has no exit, so no "quit" after "go 100" -- it
# would never be reached.
FOOTER_LINES = ["go 100"]


def build():
    ok, msg = compile_via_nova_llvm(
        SRC, OUT_INI, cpu="nova3",
        header_lines=HEADER_LINES, footer_lines=FOOTER_LINES, timeout=120,
    )
    if not ok:
        sys.exit(msg)
    print(msg)


if __name__ == "__main__":
    build()
