#!/usr/bin/env python3
"""Build gen/malloctest.ini from src/malloctest.c -- same shape as
gen_fractal.py: nova-cc, then the "set fb ..." header.

The actual compile lives in pyhelpers/simhhelpers.compile_via_nova_llvm,
shared with __testlist__vga_malloc_tester.py's test_cully_llvm_compile
step and ../cully_llvm/regen_ctestsuite.py -- this script is a thin CLI
wrapper around it, for offline regeneration outside a test run.

Requires ../cully_llvm/_toolchain/ already built -- see
../cully_llvm/NOTES.txt.

Usage: python3 gen_malloctest.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TESTSRC_HELPERDIR = "/testsrc/pyhelpers"
if TESTSRC_HELPERDIR not in sys.path:
    sys.path.insert(0, TESTSRC_HELPERDIR)
from simhhelpers import compile_via_nova_llvm

SRC = os.path.join(HERE, "src", "malloctest.c")
GEN_DIR = os.path.join(HERE, "gen")
OUT_INI = os.path.join(GEN_DIR, "malloctest.ini")

WIDTH = 640
HEIGHT = 480
PREFIX = "output/malloctest"

HEADER_LINES = [
    "; malloc/free/calloc tester for this platform's runtime",
    "; allocator -- see src/malloctest.c for what each phase",
    "; checks and why.",
    "; GENERATED BY gen_malloctest.py from src/malloctest.c via",
    "; nova-llvm-backend -- do not edit by hand.",
    "set fb width=%d" % WIDTH,
    "set fb height=%d" % HEIGHT,
    "set fb prefix=%s" % PREFIX,
]

# Unlike fractal.c, main() here returns (crt0 deposits a HALT right
# after), so "quit" after "go 100" is actually reached.
FOOTER_LINES = ["go 100", "quit"]


def build():
    ok, msg = compile_via_nova_llvm(
        SRC, OUT_INI, cpu="nova3",
        header_lines=HEADER_LINES, footer_lines=FOOTER_LINES, timeout=120,
    )
    if not ok:
        sys.exit(msg)
    print(msg)


if __name__ == "__main__":
    build()
