#!/usr/bin/env bash
# Auto-generated by test_startqemu for the 'qemu1' (m68k) VM.
# Launches QEMU with the same parameters the test runner used, so
# you can start an equivalent instance by hand on the test machine.
set -euo pipefail

exec qemu-system-m68k \
    -L \
    pc-bios \
    -M \
    q800 \
    -m \
    64 \
    -drive \
    id=hd0,file=/testsrc/m68k/pramdisk.img,format=raw,if=none \
    -device \
    scsi-hd,scsi-id=0,drive=hd0 \
    -drive \
    id=hd1,file=/testsrc/m68k/maindisk.img,format=raw,if=none \
    -device \
    scsi-hd,scsi-id=1,drive=hd1 \
    -drive \
    id=cd0,file=/testsrc/m68k/MacOS761.iso,media=cdrom,if=none \
    -device \
    scsi-cd,scsi-id=3,drive=cd0 \
    -bios \
    /testsrc/m68k/Quadra-650.ROM \
    -boot \
    d \
    -monitor \
    tcp:127.0.0.1:55555,server,nowait \
    -qmp \
    tcp:127.0.0.1:56555,server,nowait \
    -audio \
    none \
    -drive \
    id=hd2,file=/testsrc/sourcedir/mac_m68k/cuberotate/CubeRotate.dsk,format=raw,if=none \
    -device \
    scsi-hd,scsi-id=2,drive=hd2 \
    -serial \
    file:/testsrc/sourcedir/mac_m68k/cuberotate/output/serial.log
