#!/usr/bin/env python3
"""Generate FBDRAW.SR -- the RDOS assembly source for the framebuffer variant.

Proves the device is usable from real software running under RDOS, not just
from the SIMH console: the program draws a filled rectangle with word writes
and overlays a 16x16 sprite cursor in XOR mode, straddling the rectangle edge
so the same cursor is visible against both black and white.

Emitted as a paper-tape image; the test loads it with "XFER/A $PTR FBDRAW.SR",
then ASM / RLDR / run.  verify_frames.py imports the geometry from here.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# ---- frame + rectangle geometry (word aligned so the fill is pure word mode)
WIDTH = HEIGHT = 256
STRIDE = WIDTH // 16                 # 16 words per row
RECT_X, RECT_Y = 64, 48              # top-left, x must be a multiple of 16
RECT_W, RECT_H = 128, 96             # width must be a multiple of 16
RECT_WORDS = RECT_W // 16            # 8 words per row
RECT_ADDR = RECT_Y * STRIDE + RECT_X // 16

# ---- cursor ----------------------------------------------------------------
CUR_X, CUR_Y = 184, 136              # straddles the rectangle's SE corner
SPR_BASE = 0o100000                  # sprite bitmap in card RAM, past the frame
SPR_CTL = 1 | (2 << 1)               # enable | op XOR

ARROW16 = [
    "X...............",
    "XX..............",
    "XXX.............",
    "XXXX............",
    "XXXXX...........",
    "XXXXXX..........",
    "XXXXXXX.........",
    "XXXXXXXX........",
    "XXXXXXXXX.......",
    "XXXXXXXXXX......",
    "XXXXXX..........",
    "XXX.XXX.........",
    "XX..XXX.........",
    "X....XXX........",
    "......XXX.......",
    ".......XX.......",
]


def arrow_words():
    """16 words, bit 15 = leftmost pixel."""
    out = []
    for r in ARROW16:
        v = 0
        for x, c in enumerate(r):
            if c == "X":
                v |= 1 << (15 - x)
        out.append(v)
    return out


def pixel(x, y):
    """Is cursor pixel (x, y) set?  Relative to the cursor origin."""
    if not (0 <= x < 16 and 0 <= y < 16):
        return 0
    return (arrow_words()[y] >> (15 - x)) & 1


def in_rect(x, y):
    return (RECT_X <= x < RECT_X + RECT_W) and (RECT_Y <= y < RECT_Y + RECT_H)


SRC = """\
; FBDRAW -- draw a filled rectangle and overlay a sprite cursor.
; GENERATED BY gen_rdos_src.py -- do not edit by hand.
;
; Runs as an ordinary RDOS program. A Nova has no supervisor mode, so a user
; program can issue IOT to device 42 directly; the card never asserts Done and
; never interrupts, so RDOS is undisturbed by it.
        .TITL FBDRAW
        .ENT  FBDRAW
        .NREL

FBDRAW: LDA 0,CTLAI         ; word mode, address auto-increments
        DOC 0,42

; ---- filled rectangle: {rw} x {rh} at ({rx},{ry}), pure word writes ----
        LDA 0,RADR          ; AC0 = word address of the first row
        LDA 3,ROWS
        STA 3,RCNT
ROWLP:  DOA 0,42            ; latch this row's start
        LDA 1,ONES
        LDA 3,NWORD
        STA 3,WCNT
COLLP:  DOB 1,42            ; autoinc walks across the row
        DSZ WCNT
        JMP COLLP
        LDA 3,STRID
        ADD 3,0             ; AC0 = AC0 + stride, next row
        DSZ RCNT
        JMP ROWLP

; ---- copy the 16 word cursor bitmap into the card's own memory ----
        LDA 0,SPRBAS
        DOA 0,42
        LDA 2,CURPTR
        LDA 3,SIXTN
        STA 3,CCNT
CURLP:  LDA 1,0,2
        DOB 1,42
        INC 2,2
        DSZ CCNT
        JMP CURLP

; ---- sprite registers: PTR, X, Y, CTL ----
        LDA 0,CTLSPR        ; sprite register port
        DOC 0,42
        LDA 0,ZERO          ; sprite 0, register 0; the port auto-increments
        DOA 0,42
        LDA 2,REGPTR
        LDA 3,FOUR
        STA 3,RGCNT
REGLP:  LDA 1,0,2
        DOB 1,42
        INC 2,2
        DSZ RGCNT
        JMP REGLP

        NIOP 42             ; present: swap buffers, composite, dump PNG

        .SYSTM
        .RTN
        JMP  .-1

CTLAI:  {ctlai}
CTLSPR: {ctlspr}
SPRBAS: {sprbas}
RADR:   {radr}
NWORD:  {nword}
ROWS:   {rows}
STRID:  {strid}
ONES:   177777
ZERO:   0
SIXTN:  20
FOUR:   4
RCNT:   0
WCNT:   0
CCNT:   0
RGCNT:  0
CURPTR: CURSOR
REGPTR: SPREGS

CURSOR: {cursor}

SPREGS: {sprbas}
        {curx}
        {cury}
        {sctl}
        .END  FBDRAW
"""


def main():
    cur = arrow_words()
    body = SRC.format(
        rw=RECT_W, rh=RECT_H, rx=RECT_X, ry=RECT_Y,
        ctlai="%o" % 0o20000,
        ctlspr="%o" % 0o4000,
        sprbas="%o" % SPR_BASE,
        radr="%o" % RECT_ADDR,
        nword="%o" % RECT_WORDS,
        rows="%o" % RECT_H,
        strid="%o" % STRIDE,
        cursor="\n        ".join("%o" % w for w in cur),
        curx="%o" % CUR_X,
        cury="%o" % CUR_Y,
        sctl="%o" % SPR_CTL,
    )
    path = os.path.join(HERE, "src", "FBDRAW.SR")
    # Human-readable copy, CRLF like an RDOS text file.
    text = body.replace("\n", "\r\n") + "\x1a"
    with open(path, "w", newline="") as f:
        f.write(text)

    # Paper-tape image for "XFER/A $PTR FBDRAW.SR". DG 8-level tape carries a
    # parity bit in channel 8 and RDOS checks it: plain ASCII (bit 7 clear)
    # gives "PARITY ERROR: $PTR" and a corrupt file. EVEN parity is what $PTR
    # accepts -- odd parity fails the same way plain ASCII does.
    tape = bytearray()
    for ch in text.encode("ascii", "replace"):
        b = ch & 0x7F
        tape.append(b | ((bin(b).count("1") & 1) << 7))
    tape_path = os.path.join(HERE, "src", "FBDRAW.ptp")
    open(tape_path, "wb").write(bytes(tape))

    print("wrote %s (%d lines)" % (path, body.count("\n")))
    print("wrote %s (%d bytes, even parity)" % (tape_path, len(tape)))
    print("rect %dx%d at (%d,%d) -> word %o, %o words/row, %o rows"
          % (RECT_W, RECT_H, RECT_X, RECT_Y, RECT_ADDR, RECT_WORDS, RECT_H))
    print("cursor at (%d,%d), XOR op" % (CUR_X, CUR_Y))


if __name__ == "__main__":
    main()
