#!/usr/bin/env python3
"""Generate src/nova_charrom.h -- the card's built-in 8x16 ASCII character ROM.

Rasterizes DejaVu Sans Mono (free-licensed, on the box at
/usr/share/fonts/truetype/dejavu) into the same 8x16 cell IBM's VGA font uses.
13px is the size that fits: its advance is 7.83px, so glyphs sit inside the 8px
cell without clipping, where 14px (8.42px advance) would bleed into the next
column.

This is a GENERATOR, like gen_cursor.py and gen_rdos_src.py -- the header it
writes is checked in so nothing needs Pillow or a font at build time, and the
device has a font even with no display memory loaded. Re-run it only to change
the font:

    ./gen_charrom.py            # rewrites src/nova_charrom.h

WHY A ROM AT ALL, when CHARPTR can point at display memory: a program that
wants text should not have to ship 4096 words of font before it can print, and
a card with no font is a card that shows nothing on power-up. CHARPTR = 0
selects this ROM; any other value selects the user's own glyphs, so overloading
the font costs one register write and needs no cooperation from here.

FORMAT (matching the device -- see fb_text_glyph in nova_fb.c):

    one word per scanline, 16 scanlines per glyph, 256 glyphs
    glyph g scanline r is at CHARPTR + (g * 16) + r
    bits 15-8 are the 8 pixels, BIT 15 LEFTMOST, low byte zero

Bit 15 leftmost matches the framebuffer and the sprites, so every bitmap on
this card reads the same way. One word per scanline rather than two packed
scanlines because the Nova has no byte addressing outside 8-bit bus mode:
unpacking would cost a shift and a mask per row for a 2048-word saving that the
64KW of display memory does not need.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "src", "nova_charrom.h")

FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
SIZE = 13
CELL_W, CELL_H = 8, 16
# Baseline nudge: DejaVu at 13px draws ascenders from y=0 with a little room to
# spare, and 1px down centres the x-height in the 16-line cell the way the VGA
# font does.
Y_OFFSET = 1

FIRST, LAST = 0x20, 0x7E          # printable ASCII; the rest of the 256 is blank
NGLYPH = 256


def read_charrom(path=None):
    """Parse the generated header back into 4096 glyph words.

    The consumers of the ROM (gen_text.py deriving a font from it,
    verify_frames.py recomputing what char mode should have drawn) need the
    glyphs the DEVICE ships, which is this header -- not a re-render from the
    TTF, which would only prove Pillow is deterministic and would need Pillow
    installed to check anything.
    """
    words, inside = [], False
    for line in open(path or OUT):
        if not inside:
            # Only the array body is data; the header comment above it has
            # numbers in the prose ("256 glyphs") that parse as octal.
            inside = "fb_charrom[" in line and "{" in line
            continue
        if "};" in line:
            break
        for tok in line.split("/*")[0].split(","):
            tok = tok.strip()
            if not tok:
                continue
            try:
                words.append(int(tok, 8))
            except ValueError:
                pass
    if len(words) != NGLYPH * CELL_H:
        raise ValueError("%s: expected %d glyph words, parsed %d"
                         % (path or OUT, NGLYPH * CELL_H, len(words)))
    return words


def render():
    from PIL import Image, ImageDraw, ImageFont

    if not os.path.exists(FONT):
        sys.exit("gen_charrom: no font at %s" % FONT)
    font = ImageFont.truetype(FONT, SIZE)

    glyphs = [[0] * CELL_H for _ in range(NGLYPH)]
    for code in range(FIRST, LAST + 1):
        img = Image.new("1", (CELL_W, CELL_H), 0)
        ImageDraw.Draw(img).text((0, Y_OFFSET), chr(code), font=font, fill=1)
        px = img.load()
        for row in range(CELL_H):
            bits = 0
            for col in range(CELL_W):
                if px[col, row]:
                    bits |= 1 << (7 - col)      # col 0 is the leftmost pixel
            glyphs[code][row] = bits << 8       # into bits 15-8
    return glyphs


def emit(glyphs):
    lines = []
    lines.append("/* nova_charrom.h: built-in 8x16 ASCII character ROM for nova_fb.")
    lines.append("")
    lines.append("   GENERATED BY gen_charrom.py -- do not edit by hand.")
    lines.append("")
    lines.append("   Rasterized from DejaVu Sans Mono at %dpx into the 8x16 cell the VGA"
                 % SIZE)
    lines.append("   font uses. One word per scanline, 16 scanlines per glyph, 256")
    lines.append("   glyphs; bits 15-8 are the pixels, bit 15 leftmost, matching the")
    lines.append("   framebuffer and sprite bit order. Codes %#04x-%#04x are printable"
                 % (FIRST, LAST))
    lines.append("   ASCII; everything else is blank, and a program that wants those")
    lines.append("   codes points CHARPTR at its own table instead. */")
    lines.append("")
    lines.append("#define FB_CHARROM_GLYPHS   %d" % NGLYPH)
    lines.append("#define FB_CHAR_H           %d" % CELL_H)
    lines.append("#define FB_CHAR_W           %d" % CELL_W)
    lines.append("")
    lines.append("static const uint16 fb_charrom[FB_CHARROM_GLYPHS * FB_CHAR_H] = {")
    for code in range(NGLYPH):
        rows = glyphs[code]
        if any(rows):
            ch = chr(code)
            label = "'%s'" % ch if ch not in ("'", "\\") else "%#04x" % code
            lines.append("    /* %#04x %s */" % (code, label))
            for i in range(0, CELL_H, 8):
                lines.append("    " + " ".join("0%06o," % w for w in rows[i:i + 8]))
        else:
            lines.append("    /* %#04x blank */" % code)
            lines.append("    " + " ".join(["0,"] * 8))
            lines.append("    " + " ".join(["0,"] * 8))
    lines.append("    };")
    lines.append("")
    return "\n".join(lines)


def main():
    glyphs = render()
    text = emit(glyphs)
    with open(OUT, "w") as f:
        f.write(text)
    filled = sum(1 for g in glyphs if any(g))
    print("wrote %s (%d glyphs, %d words)"
          % (OUT, filled, NGLYPH * CELL_H))

    # A font nobody can read is the failure mode worth catching here, since the
    # device will happily render blanks. Print a couple of glyphs as ASCII art.
    for code in (ord("A"), ord("g")):
        print("\n  %s:" % chr(code))
        for row in glyphs[code]:
            bits = (row >> 8) & 0xFF
            print("    " + "".join("#" if bits & (1 << (7 - c)) else "."
                                   for c in range(8)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
