#!/usr/bin/env python3
"""Generate the sprite cursor demos for the nova_fb device.

Builds a 32x32 arrow cursor out of FOUR 16x16 sprite units (one per quadrant),
which is what the 4 sprite units are for.  Emits demo/cursor.ini (SET op) and
demo/cursor_xor.ini (XOR op).  verify_frames.py imports ARROW32 from here to
recompute the expected image independently of the simulator.
"""
import os

DEMO = os.path.join(os.path.dirname(os.path.abspath(__file__)), "demo")

# Filled arrow, 16x16.  Scaled 2x below to 32x32.
ARROW16 = [
    "X...............",
    "XX..............",
    "XXX.............",
    "XXXX............",
    "XXXXX...........",
    "XXXXXX..........",
    "XXXXXXX.........",
    "XXXXXXXX........",
    "XXXXXXXXX.......",
    "XXXXXXXXXX......",
    "XXXXXX..........",
    "XXX.XXX.........",
    "XX..XXX.........",
    "X....XXX........",
    "......XXX.......",
    ".......XX.......",
]


def scale2x(rows):
    """Double each row and each pixel -> 32x32 list of 32-bit ints."""
    out = []
    for r in rows:
        v = 0
        for x, c in enumerate(r):
            if c == "X":
                v |= (3 << (30 - 2 * x))        # two adjacent pixels
        out.append(v)
        out.append(v)
    return out


ARROW32 = scale2x(ARROW16)                       # 32 rows, bit31 = leftmost


def quadrants():
    """Split ARROW32 into 4 16x16 sprites: TL, TR, BL, BR (bit15 = leftmost)."""
    tl = [(ARROW32[y] >> 16) & 0xFFFF for y in range(16)]
    tr = [ARROW32[y] & 0xFFFF for y in range(16)]
    bl = [(ARROW32[y] >> 16) & 0xFFFF for y in range(16, 32)]
    br = [ARROW32[y] & 0xFFFF for y in range(16, 32)]
    return tl, tr, bl, br


def pixel(x, y):
    """Is arrow pixel (x, y) set?  x, y relative to the cursor hot corner."""
    if not (0 <= x < 32 and 0 <= y < 32):
        return 0
    return (ARROW32[y] >> (31 - x)) & 1


# ---- layout -----------------------------------------------------------------
SPR_BASE = 0o100000          # sprite bitmaps in card RAM, well past the frame
TBL_BITMAP = 0o1000          # Nova RAM: 64 bitmap words
TBL_REGS1 = 0o1200           # Nova RAM: 16 sprite registers, position 1
TBL_REGS2 = 0o1220           # Nova RAM: 16 sprite registers, position 2

POS1 = (100, 50)             # frame 1 cursor position
POS2 = (240, 240)            # frame 2: hangs off the bottom-right, tests clip

BG = 0o125252                # background stripe pattern (0xAAAA)
WIDTH = HEIGHT = 256


def sprite_regs(cx, cy, op):
    """16 words: 4 sprites x (PTR, X, Y, CTL)."""
    ctl = 1 | (op << 1)                          # bit0 enable, bits2-1 op
    quad_off = [(0, 0, 0), (16, 16, 0), (32, 0, 16), (48, 16, 16)]
    regs = []
    for base, dx, dy in quad_off:
        regs += [SPR_BASE + base, (cx + dx) & 0xFFFF, (cy + dy) & 0xFFFF, ctl]
    return regs


def emit(path, op, comment):
    tl, tr, bl, br = quadrants()
    bitmap = tl + tr + bl + br                   # 64 words
    r1 = sprite_regs(POS1[0], POS1[1], op)
    r2 = sprite_regs(POS2[0], POS2[1], op)

    L = []
    a = L.append
    a("; %s" % comment)
    a("; GENERATED BY gen_cursor.py -- do not edit by hand.")
    a("; A 32x32 arrow built from FOUR 16x16 sprite units, one per quadrant.")
    a("; Sprite bitmaps live in the card's OWN display memory at %o and are"
      % SPR_BASE)
    a("; reached through each sprite's PTR register, VIC-II style. A 0 bit is")
    a("; transparent, so there is no mask plane.")
    a("; Frame 1 puts the cursor at %s; frame 2 moves it to %s, which hangs"
      % (POS1, POS2))
    a("; off the bottom-right corner and must clip, not wrap. Frame 2 also")
    a("; proves the overlay never damaged the background at the old position.")
    a("set fb width=%d" % WIDTH)
    a("set fb height=%d" % HEIGHT)
    a("set fb prefix=output/%s" % os.path.basename(path).replace(".ini", ""))
    a("; --- page zero constants ---")
    a("d 50 0")                                   # zero / start
    a("d 51 %o" % BG)                             # background pattern
    a("d 52 20000")                               # ctl AUTOINC
    a("d 53 %o" % ((WIDTH // 16) * HEIGHT))       # background word count
    a("d 54 %o" % SPR_BASE)                       # card RAM sprite base
    a("d 55 %o" % TBL_BITMAP)                     # Nova bitmap table
    a("d 56 %o" % len(bitmap))                    # 64
    a("d 57 4000")                                # ctl SPRITE
    a("d 60 %o" % TBL_REGS1)
    a("d 61 %o" % len(r1))                        # 16
    a("d 62 %o" % TBL_REGS2)
    a("d 63 %o" % len(r2))                        # 16
    a("; --- sprite bitmap table (64 words: TL, TR, BL, BR) ---")
    for i, w in enumerate(bitmap):
        a("d %o %o" % (TBL_BITMAP + i, w))
    a("; --- sprite registers, position 1 (PTR, X, Y, CTL per unit) ---")
    for i, w in enumerate(r1):
        a("d %o %o" % (TBL_REGS1 + i, w))
    a("; --- sprite registers, position 2 ---")
    for i, w in enumerate(r2):
        a("d %o %o" % (TBL_REGS2 + i, w))
    a("; --- phase 1: fill the background with stripes (word mode, AUTOINC) ---")
    a("d 100 20052")      # LDA 0,52   ctl AUTOINC
    a("d 101 63042")      # DOC 0,42
    a("d 102 20050")      # LDA 0,50   addr 0
    a("d 103 61042")      # DOA 0,42
    a("d 104 24051")      # LDA 1,51   pattern
    a("d 105 66042")      # DOB 1,42   <- loop
    a("d 106 14053")      # DSZ 53
    a("d 107 000105")     # JMP
    a("; --- phase 2: copy sprite bitmaps into card RAM at %o ---" % SPR_BASE)
    a("d 110 20054")      # LDA 0,54   card addr
    a("d 111 61042")      # DOA 0,42
    a("d 112 30055")      # LDA 2,55   AC2 = table pointer
    a("d 113 25000")      # LDA 1,0,2  <- loop, indexed by AC2
    a("d 114 66042")      # DOB 1,42
    a("d 115 151400")     # INC 2,2
    a("d 116 14056")      # DSZ 56
    a("d 117 000113")     # JMP
    a("; --- phase 3: load 16 sprite registers (sprite mode) ---")
    a("d 120 20057")      # LDA 0,57   ctl SPRITE
    a("d 121 63042")      # DOC 0,42
    a("d 122 20050")      # LDA 0,50   sprite reg addr 0
    a("d 123 61042")      # DOA 0,42
    a("d 124 30060")      # LDA 2,60
    a("d 125 25000")      # LDA 1,0,2  <- loop
    a("d 126 66042")      # DOB 1,42
    a("d 127 151400")     # INC 2,2
    a("d 130 14061")      # DSZ 61
    a("d 131 000125")     # JMP
    a("; --- phase 4: present frame 1 ---")
    a("d 132 60342")      # NIOP 42
    a("; --- phase 5: move the cursor (16 register writes) and present ---")
    a("d 133 20050")      # LDA 0,50
    a("d 134 61042")      # DOA 0,42
    a("d 135 30062")      # LDA 2,62
    a("d 136 25000")      # LDA 1,0,2  <- loop
    a("d 137 66042")      # DOB 1,42
    a("d 140 151400")     # INC 2,2
    a("d 141 14063")      # DSZ 63
    a("d 142 000136")     # JMP
    a("d 143 60342")      # NIOP 42
    a("d 144 63077")      # HALT
    a("go 100")
    a("e fb frame")
    a("quit")
    open(path, "w").write("\n".join(L) + "\n")
    print("wrote %s (%d lines)" % (path, len(L)))


if __name__ == "__main__":
    emit(os.path.join(DEMO, "cursor.ini"), 0,
         "Sprite cursor, SET op: solid arrow over a striped background.")
    emit(os.path.join(DEMO, "cursor_xor.ini"), 2,
         "Sprite cursor, XOR op: inverts the background, so it stays visible "
         "over any content -- what the mask plane was really buying.")
