#!/usr/bin/env python3
"""Assert the live view sink agrees with the PNG the same present wrote.

The card publishes each frame twice, by two independent code paths: a 1-bit PNG
(SET FB PREFIX) and a shared memory sink (SET FB LIVE). verify_frames.py checks
the PNGs against recomputed pixels, so the PNG is the trusted reference; this
checks the sink against it. If they ever diverge, what a viewer shows is no
longer what the assertions assert, which is the failure worth catching.

Headless on purpose -- no pygame, no X, no viewer. It exercises the sink and
the reader (pyhelpers/novafbhelpers.py), not the window.

    ./verify_live.py [demo]        default: cursor

Exits non-zero on any mismatch, so it drops into a testlist as a
test_hostbuild step exactly like verify_frames.py does.
"""

import os
import struct
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, "/testsrc/pyhelpers")

from verify_frames import read_png                      # noqa: E402

try:
    from novafbhelpers import (MAGIC, NovaFbLive, VERSION,  # noqa: E402
                               frame_to_rgb)
except ImportError as exc:
    sys.stderr.write("verify_live: cannot import the reader from "
                     "/testsrc/pyhelpers (%s)\n" % exc)
    raise SystemExit(2)

try:
    from simhhelpers import NovaSimhInstance                # noqa: E402
except ImportError as exc:
    sys.stderr.write("verify_live: cannot import NovaSimhInstance from "
                     "/testsrc/pyhelpers (%s)\n" % exc)
    raise SystemExit(2)

NOVA = os.path.join(HERE, "bin", "dgnova-fb")

FAILURES = []


def check(name, cond, detail=""):
    print("  %-4s %s%s" % ("ok" if cond else "FAIL", name,
                           ("  -- " + detail) if (detail and not cond) else ""))
    if not cond:
        FAILURES.append(name)


class _Result(object):
    """subprocess.run()-shaped enough for main()'s checks below."""
    def __init__(self, returncode, output):
        self.returncode = returncode
        self.stdout = output
        self.stderr = ""


def run_demo(demo, sink, prefix):
    """Run demo/<demo>.ini with both sinks pointed somewhere disposable.

    Uses NovaSimhInstance (a pty, not a plain pipe) rather than a bare
    subprocess.run: the text80/text30/text_font demos generated by
    gen_text.py block on a console read before presenting (see its
    program()), and SIMH only polls the console at all when stdin is a real
    tty -- on a plain pipe the wait can never be satisfied, no matter what
    gets written to it. Poking "go" a few times is harmless for demos that
    never read the console (cursor, rdos_fbdraw): nothing in them looks at
    TTI, so the bytes just sit unread until the process exits.
    """
    script = os.path.join(HERE, "demo", "%s.ini" % demo)
    if not os.path.exists(script):
        raise SystemExit("verify_live: no such demo: %s" % script)

    inst = NovaSimhInstance("verify_live", binary=NOVA, script_path=script,
                            cwd=HERE, live_path=sink)
    inst.start()
    try:
        # Matches __testlist__nova_fb_textmode.py's pattern: the first send
        # always lands before SIMH switches the console into run mode and
        # gets discarded there, so it takes at least two.
        for delay in (1.5, 1.0, 1.0):
            inst.send_command("go")
            time.sleep(delay)
        try:
            returncode = inst.process.wait(timeout=110)
        except subprocess.TimeoutExpired:
            returncode = -1
    finally:
        inst.stop()
    return _Result(returncode, inst.buf)


def main(argv=None):
    argv = list(argv if argv is not None else sys.argv[1:])
    demo = argv[0] if argv else "cursor"

    sink = os.path.join("/dev/shm", "novafb-verify-%d" % os.getpid())
    # The demo sets its own "set fb prefix=output/<demo>"; those PNGs are the
    # reference and run_demos.sh regenerates them anyway.
    prefix = os.path.join("output", demo)

    if os.path.exists(sink):
        os.unlink(sink)

    print("%s.ini -- live sink vs PNG" % demo)
    proc = run_demo(demo, sink, prefix)
    check("simulator ran", proc.returncode == 0,
          (proc.stderr or proc.stdout)[-300:])
    check("sink was created", os.path.exists(sink))
    if FAILURES:
        return 1

    try:
        live = NovaFbLive(sink).open()
        try:
            hdr = struct.unpack("<16I", live._map[:64])
            check("magic is NVFB", hdr[0] == MAGIC, "%#x" % hdr[0])
            check("protocol v%d" % VERSION, hdr[1] == VERSION, str(hdr[1]))
            check("seq is even (no writer mid-copy)", hdr[7] % 2 == 0)

            frame = live.read(only_new=False)
            check("a frame is readable", frame is not None)
            if frame is None:
                return 1

            png = os.path.join(HERE, "%s%04d.png" % (prefix, frame.frame))
            check("matching PNG exists (%s)" % os.path.basename(png),
                  os.path.exists(png))
            if not os.path.exists(png):
                return 1

            w, h, rows = read_png(png)
            check("geometry matches the PNG",
                  (frame.width, frame.height) == (w, h),
                  "sink %dx%d, png %dx%d" % (frame.width, frame.height, w, h))
            check("stride matches the PNG", frame.stride == len(rows[0]),
                  "sink %d, png %d" % (frame.stride, len(rows[0])))
            check("payload is byte-identical to the PNG raster",
                  frame.pixels == b"".join(rows))
            check("frame counter is the last present", frame.frame >= 1,
                  str(frame.frame))

            # The unpacking a viewer actually draws through, spot-checked
            # against the packed bits rather than trusted.
            rgb = frame_to_rgb(frame)
            check("rgb expansion is %d bytes" % (w * h * 3),
                  len(rgb) == w * h * 3, str(len(rgb)))
            bad = 0
            for y in range(h):
                row = rows[y]
                for x in range(w):
                    bit = (row[x // 8] >> (7 - (x % 8))) & 1
                    if rgb[(y * w + x) * 3] != (255 if bit else 0):
                        bad += 1
            check("every pixel expands white-on-black correctly", bad == 0,
                  "%d wrong" % bad)
        finally:
            live.close()
    finally:
        if os.path.exists(sink):
            os.unlink(sink)

    print()
    if FAILURES:
        print("LIVE CHECKS FAILED: %s" % ", ".join(FAILURES))
        return 1
    print("ALL LIVE CHECKS PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
