#!/usr/bin/env python3
"""screen_runtime.py -- run every gen/*.ini (see regen_ctestsuite.py) once,
directly against dgnova with a hard timeout, and classify PASS / FAIL /
HANG. Same shape as ../nova_ctestsuite/screen_runtime.py: a clean build
does NOT mean a clean run -- e.g. an LLVM codegen bug that produces
*wrong* code instead of crashing at build time would only show up here.

gen_testlists.py wires PASS results into the normal batchNN testlists,
AND wires FAIL/HANG results into separate "known issue" testlists -- see
that script's own header for the skip-cascade caveat this carries over
unchanged from the nova_ctestsuite convention.

Usage: python3 screen_runtime.py
Writes RUNTIME_STATUS.md, stable_pass.txt, and known_issues.txt (one test
basename per line each, consumed by gen_testlists.py).
"""
import glob
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GEN_DIR = os.path.join(HERE, "gen")
STATUS_PATH = os.path.join(HERE, "RUNTIME_STATUS.md")
STABLE_PASS_PATH = os.path.join(HERE, "stable_pass.txt")
KNOWN_ISSUES_PATH = os.path.join(HERE, "known_issues.txt")

_VENDORED_DGNOVA = "/testsrc/disk_artifacts/bin/dgnova"
DGNOVA_BIN = _VENDORED_DGNOVA if os.path.exists(_VENDORED_DGNOVA) else "dgnova"

TIMEOUT_SECONDS = 10


def classify(ini_path):
    try:
        r = subprocess.run(
            [DGNOVA_BIN, ini_path],
            capture_output=True, text=True, timeout=TIMEOUT_SECONDS,
        )
        out = r.stdout + r.stderr
    except subprocess.TimeoutExpired:
        return "HANG", ""
    if "PASS" in out:
        return "PASS", out
    if "FAIL" in out:
        return "FAIL", out
    return "HANG", out  # ran to completion with neither phrase -- treat as unclassifiable/unsafe


def main():
    ini_files = sorted(glob.glob(os.path.join(GEN_DIR, "*.ini")))
    if not ini_files:
        sys.exit(f"no .ini files under {GEN_DIR} -- run regen_ctestsuite.py first")

    results = {}
    for ini_path in ini_files:
        base = os.path.splitext(os.path.basename(ini_path))[0]
        status, _ = classify(ini_path)
        results[base] = status
        print(f"{base}: {status}")

    stable_pass = sorted(b for b, s in results.items() if s == "PASS")
    fails = sorted(b for b, s in results.items() if s == "FAIL")
    hangs = sorted(b for b, s in results.items() if s == "HANG")

    with open(STABLE_PASS_PATH, "w") as f:
        f.write("\n".join(stable_pass) + "\n")

    known_issues = sorted(fails) + sorted(hangs)
    with open(KNOWN_ISSUES_PATH, "w") as f:
        f.write("\n".join(f"{b},{results[b]}" for b in known_issues) + "\n")

    with open(STATUS_PATH, "w") as f:
        f.write("# cully_llvm runtime status\n\n")
        f.write(
            "Auto-generated by screen_runtime.py -- do not hand-edit. Each "
            f"gen/*.ini run once against dgnova with a {TIMEOUT_SECONDS}s "
            "timeout.\n\n"
        )
        f.write(f"**{len(stable_pass)} / {len(results)} stable PASS** (wired into the batchNN testlists)\n\n")
        f.write(f"## Runtime FAIL ({len(fails)}) -- built and ran, wrong answer\n\n")
        for b in fails:
            f.write(f"- {b}\n")
        f.write(f"\n## HANG / timeout ({len(hangs)})\n\n")
        for b in hangs:
            f.write(f"- {b}\n")

    print(f"\n{len(stable_pass)} stable PASS, {len(fails)} FAIL, {len(hangs)} HANG")
    print(f"wrote {STABLE_PASS_PATH}")
    print(f"wrote {KNOWN_ISSUES_PATH}")
    print(f"wrote {STATUS_PATH}")


if __name__ == "__main__":
    main()
